# Site settings
title: asiertejada.com
email: asiertejada@gmail.com
description: El blog de Asier Tejada Osegui
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.asiertejada.com" # the base hostname & protocol for your site
#url: "http://127.0.0.1:4000" # for local testing
logo: logo.png
excerpt_separator: <Sigue Leyendo>
timezone: 'Europe/Madrid'

# Social settings
twitter_username: asiertejada
facebook_username: asiertejada
github_username:  asiertejada
deviantart_username: ptt69bio
dribbble_username: asiertejada
medium_username: asiertejada

# Analytics tracking code
google_analytics: UA-40728880-1

# Build settings
markdown: kramdown
permalink: /:title/
paginate:    5
paginate_path: "page:num"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
